include: package:effective_dart/analysis_options.yaml

linter:
  rules:
    parameter_assignments: true
    prefer_relative_imports: false
    public_member_api_docs: false
    prefer_mixin: false
    one_member_abstracts: false
    type_annotate_public_apis: false
    unnecessary_lambdas: false
    avoid_catches_without_on_clauses: false
    lines_longer_than_80_chars: false

analyzer:
  enable-experiment:
    - extension-methods
  errors:
    missing_required_param: error
