name: flyme_app
description: A new Flutter project.

# The following line prevents the package from being accidentally published to
# pub.dev using `pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
version: 1.0.0+1

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter

  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^0.1.3

  # responsive layout
  responsive_builder: ^0.2.0+2
  # SwiftUI 方式编写 UI
  velocity_x: ^0.4.0
  styled_widget: ^0.2.1+2
  flushbar: ^1.10.4
  # 引导页中的"点"
  dots_indicator: ^1.1.0
  # 轮播图
  flutter_swiper: ^1.1.6
  # loading
  flutter_spinkit: ^4.1.2
  # shimmer
  shimmer: ^1.1.1
  provider: ^4.1.2
  fluro: ^1.6.3
  dio: ^3.0.9
  tuple: ^1.0.3
  shared_preferences: ^0.5.7+3
  # NoSQL 数据库
  hive: ^1.4.1+1
  hive_flutter: ^0.3.0+2
  # JSON 转换类注解
  json_annotation: ^3.0.1
  cached_network_image: ^2.2.0+1
  event_bus: ^1.1.1
  # Service locator
  get_it: ^4.0.2
  injectable: ^0.4.0
  # Value equality
  equatable: ^1.1.1
  # Functional programming thingies
  dartz: ^0.9.1
  # Dart Method Extensions
  dartx: ^0.4.1
  sprintf: ^4.0.2
  oktoast: ^2.3.2
  # Google fonts
  google_fonts: ^1.1.0
  # 图标库
  flutter_icons: 1.1.0
  # 闪退日志收集
  catcher: ^0.3.7
  # 生成器注解
  freezed_annotation: ^0.7.1
  flyme_annotation:
    git:
      url: https://github.com/maybewaityou/flyme_annotation.git

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_driver:
    sdk: flutter
  test: any

  # 编码规范
  effective_dart: ^1.2.1

  # mock
  mockito: ^4.1.1
  build_runner: ^1.10.0
  json_serializable: ^3.3.0
  logging: ^0.11.4
  flutter_stetho: ^0.5.2
  # NoSQL 数据库生成器
#  hive_generator: ^0.7.0+2
  hive_generator: any
  # 生成器
  injectable_generator: ^0.4.0
  intl_utils: ^1.5.0
  freezed: ^0.10.9
  flyme_generator:
    git:
      url: https://github.com/maybewaityou/flyme_generator.git

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  # assets:
  #  - images/a_dot_burr.jpeg
  #  - images/a_dot_ham.jpeg

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware.

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
flutter_intl:
  enabled: true # Required. Must be set to true to activate the plugin. Default: false
  class_name: S # Optional. Sets the name for the generated localization class. Default: S
  main_locale: en # Optional. Sets the main locale used for generating localization files. Provided value should comply with ISO-639-1 and ISO-3166-1 (e.g. "en", "en_GB"). Default: en
